### ISSUE TITLE
Azure ML Add On Installation Error

### ISSUE THREAD

**Issue by KjellRSeeq** [seeq12/seeq-azureml#2] opened 2021-11-09 20:11 UTC
I am running into an error when I get to Step 3 of the installation instructions. See snippet below.
![image](https://user-images.githubusercontent.com/92815457/140995032-f079430f-65e1-405c-b99a-728c5a526621.png)

The steps taken prior to Step 2 from instructions, to ensure SPy version xx.x.x.182.25:
`pip uninstall seeq`
`pip install seeq==52.3.2.182.25 -U`

I also had similar issues with installing the MPS Add On, per ticket here: https://github.com/seeq12/seeq-mps/issues/1 but that was resolved after following the 2 steps above to install that version of seeq module (and then I manually loaded the notebook's appmode link into the External Tools manager).

I also tried just running `pip install seeq==52.3.2.182.25 -U` without the uninstall before it, and that yielded the same result.
![image](https://user-images.githubusercontent.com/92815457/140997304-4eacd933-3148-4720-88f2-b8dca4b3ff8d.png)

Full terminal trace:
`datalab@jupyter:~$ pip install seeq==52.3.2.182.25 -U
Collecting seeq==52.3.2.182.25
  Downloading seeq-52.3.2.182.25-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 7.5 MB/s
Requirement already satisfied: ipywidgets>=7.5.1 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (7.6.3)
Requirement already satisfied: Deprecated>=1.2.6 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (1.2.6)
Requirement already satisfied: requests>=2.21.0 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (2.25.1)
Requirement already satisfied: pyOpenSSL>=19.1.0 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (20.0.1)
Requirement already satisfied: pandas>=1.0.0 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (1.2.3)
Requirement already satisfied: six>=1.10 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (1.16.0)
Requirement already satisfied: notebook>=6.0.0 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (6.4.0)
Requirement already satisfied: cron-descriptor>=1.2.24 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (1.2.24)
Requirement already satisfied: beautifulsoup4>=4.8.0 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (4.9.3)
Requirement already satisfied: urllib3>=1.15.1 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (1.26.4)
Requirement already satisfied: numpy>=1.16.4 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (1.20.1)
Requirement already satisfied: cryptography>=3.2 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (3.4.4)
Requirement already satisfied: nbconvert==5.5.0 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (5.5.0)
Requirement already satisfied: certifi>=14.05.14 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (2021.5.30)
Requirement already satisfied: Mako>=1.1.0 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (1.1.4)
Requirement already satisfied: ipython>=7.6.1 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (7.24.1)
Requirement already satisfied: matplotlib>=3.1.1 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (3.3.4)
Requirement already satisfied: recurrent>=0.4.0 in /opt/conda/lib/python3.8/site-packages (from seeq==52.3.2.182.25) (0.4.0)
Collecting Markdown>=3.3.4
  Downloading Markdown-3.3.4-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 40.0 MB/s
Requirement already satisfied: mistune>=0.8.1 in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (0.8.4)
Requirement already satisfied: jinja2>=2.4 in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (3.0.1)
Requirement already satisfied: pygments in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (2.9.0)
Requirement already satisfied: bleach in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25)(3.3.0)
Requirement already satisfied: jupyter-core in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (4.7.1)
Requirement already satisfied: testpath in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (0.5.0)
Requirement already satisfied: traitlets>=4.2 in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (5.0.5)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (1.4.3)
Requirement already satisfied: entrypoints>=0.2.2 in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (0.3)
Requirement already satisfied: defusedxml in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (0.7.1)
Requirement already satisfied: nbformat>=4.4 in /opt/conda/lib/python3.8/site-packages (from nbconvert==5.5.0->seeq==52.3.2.182.25) (5.1.3)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.8/site-packages (from beautifulsoup4>=4.8.0->seeq==52.3.2.182.25) (2.0.1)
Requirement already satisfied: cffi>=1.12 in /opt/conda/lib/python3.8/site-packages (from cryptography>=3.2->seeq==52.3.2.182.25) (1.14.5)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=3.2->seeq==52.3.2.182.25) (2.20)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/conda/lib/python3.8/site-packages (from Deprecated>=1.2.6->seeq==52.3.2.182.25) (1.12.1)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.8/site-packages (from ipython>=7.6.1->seeq==52.3.2.182.25) (0.7.5)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.8/site-packages (from ipython>=7.6.1->seeq==52.3.2.182.25) (4.8.0)
Requirement already satisfied: backcall in /opt/conda/lib/python3.8/site-packages (from ipython>=7.6.1->seeq==52.3.2.182.25)(0.2.0)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.8/site-packages (from ipython>=7.6.1->seeq==52.3.2.182.25) (0.18.0)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/lib/python3.8/site-packages (from ipython>=7.6.1->seeq==52.3.2.182.25) (57.0.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.8/site-packages (from ipython>=7.6.1->seeq==52.3.2.182.25) (5.0.9)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.8/site-packages (from ipython>=7.6.1->seeq==52.3.2.182.25) (0.1.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from ipython>=7.6.1->seeq==52.3.2.182.25) (3.0.18)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets>=7.5.1->seeq==52.3.2.182.25) (1.0.0)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.8/site-packages (from ipywidgets>=7.5.1->seeq==52.3.2.182.25) (5.5.5)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets>=7.5.1->seeq==52.3.2.182.25) (3.5.1)
Requirement already satisfied: tornado>=4.2 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->seeq==52.3.2.182.25) (6.1)
Requirement already satisfied: jupyter-client in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->seeq==52.3.2.182.25) (6.1.12)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.8/site-packages (from jedi>=0.16->ipython>=7.6.1->seeq==52.3.2.182.25) (0.8.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.8/site-packages (from jinja2>=2.4->nbconvert==5.5.0->seeq==52.3.2.182.25) (2.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.8/site-packages (from matplotlib>=3.1.1->seeq==52.3.2.182.25) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /opt/conda/lib/python3.8/site-packages (from matplotlib>=3.1.1->seeq==52.3.2.182.25) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.8/site-packages (from matplotlib>=3.1.1->seeq==52.3.2.182.25) (8.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.8/site-packages (from matplotlib>=3.1.1->seeq==52.3.2.182.25) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /opt/conda/lib/python3.8/site-packages (from matplotlib>=3.1.1->seeq==52.3.2.182.25) (2.8.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/conda/lib/python3.8/site-packages (from nbformat>=4.4->nbconvert==5.5.0->seeq==52.3.2.182.25) (3.2.0)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.8/site-packages (from nbformat>=4.4->nbconvert==5.5.0->seeq==52.3.2.182.25) (0.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /opt/conda/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert==5.5.0->seeq==52.3.2.182.25) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in /opt/conda/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert==5.5.0->seeq==52.3.2.182.25) (21.2.0)
Requirement already satisfied: Send2Trash>=1.5.0 in /opt/conda/lib/python3.8/site-packages (from notebook>=6.0.0->seeq==52.3.2.182.25) (1.5.0)
Requirement already satisfied: prometheus-client in /opt/conda/lib/python3.8/site-packages (from notebook>=6.0.0->seeq==52.3.2.182.25) (0.11.0)
Requirement already satisfied: terminado>=0.8.3 in /opt/conda/lib/python3.8/site-packages (from notebook>=6.0.0->seeq==52.3.2.182.25) (0.10.0)
Requirement already satisfied: argon2-cffi in /opt/conda/lib/python3.8/site-packages (from notebook>=6.0.0->seeq==52.3.2.182.25) (20.1.0)
Requirement already satisfied: pyzmq>=17 in /opt/conda/lib/python3.8/site-packages (from notebook>=6.0.0->seeq==52.3.2.182.25) (22.1.0)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas>=1.0.0->seeq==52.3.2.182.25) (2021.1)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.8/site-packages (from pexpect>4.3->ipython>=7.6.1->seeq==52.3.2.182.25) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.6.1->seeq==52.3.2.182.25) (0.2.5)
Requirement already satisfied: parsedatetime in /opt/conda/lib/python3.8/site-packages (from recurrent>=0.4.0->seeq==52.3.2.182.25) (2.6)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/conda/lib/python3.8/site-packages (from requests>=2.21.0->seeq==52.3.2.182.25) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.8/site-packages (from requests>=2.21.0->seeq==52.3.2.182.25) (2.10)
Requirement already satisfied: packaging in /opt/conda/lib/python3.8/site-packages (from bleach->nbconvert==5.5.0->seeq==52.3.2.182.25) (20.9)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.8/site-packages (from bleach->nbconvert==5.5.0->seeq==52.3.2.182.25) (0.5.1)
Installing collected packages: Markdown, seeq
Successfully installed Markdown-3.3.4 seeq-52.3.2.182.25
datalab@jupyter:~$ pip install seeq-azureml
Collecting seeq-azureml
  Downloading seeq_azureml-0.1.0-py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 8.3 MB/s
Collecting ipyvuetify>=1.8.0
  Downloading ipyvuetify-1.8.1-py2.py3-none-any.whl (11.7 MB)
     |████████████████████████████████| 11.7 MB 11.6 MB/s
Requirement already satisfied: ipywidgets>=7.6.3 in /opt/conda/lib/python3.8/site-packages (from seeq-azureml) (7.6.3)
Collecting requests>=2.26.0
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 15.3 MB/s
Collecting ipydatetime>=1.2.0
  Downloading ipydatetime-1.2.0-py2.py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 42.7 MB/s
Collecting traitlets>=5.1.0
  Downloading traitlets-5.1.1-py3-none-any.whl (102 kB)
     |████████████████████████████████| 102 kB 39.9 MB/s
Requirement already satisfied: numpy>=1.19.5 in /opt/conda/lib/python3.8/site-packages (from seeq-azureml) (1.20.1)
Collecting pandas~=1.2.5
  Downloading pandas-1.2.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 17.9 MB/s
Requirement already satisfied: ipyvue<2,>=1.5 in /opt/conda/lib/python3.8/site-packages (from ipyvuetify>=1.8.0->seeq-azureml) (1.5.0)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.8/site-packages (from ipywidgets>=7.6.3->seeq-azureml) (5.5.5)
Requirement already satisfied: ipython>=4.0.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets>=7.6.3->seeq-azureml) (7.24.1)
Requirement already satisfied: nbformat>=4.2.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets>=7.6.3->seeq-azureml) (5.1.3)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets>=7.6.3->seeq-azureml) (1.0.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets>=7.6.3->seeq-azureml) (3.5.1)
Requirement already satisfied: jupyter-client in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.3->seeq-azureml) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.3->seeq-azureml) (6.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.8/site-packages (from ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (0.18.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.8/site-packages (from ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (5.0.9)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.8/site-packages (from ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (4.8.0)
Requirement already satisfied: pygments in /opt/conda/lib/python3.8/site-packages (from ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (2.9.0)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.8/site-packages (from ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (0.7.5)
Requirement already satisfied: backcall in /opt/conda/lib/python3.8/site-packages (from ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (0.2.0)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.8/site-packages (from ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (0.1.2)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/lib/python3.8/site-packages (from ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (57.0.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (3.0.18)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.8/site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (0.8.2)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.6.3->seeq-azureml) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/conda/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.6.3->seeq-azureml) (3.2.0)
Requirement already satisfied: jupyter-core in /opt/conda/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.6.3->seeq-azureml) (4.7.1)
Requirement already satisfied: attrs>=17.4.0 in /opt/conda/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.6.3->seeq-azureml) (21.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /opt/conda/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.6.3->seeq-azureml) (0.17.3)
Requirement already satisfied: six>=1.11.0 in /opt/conda/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.6.3->seeq-azureml) (1.16.0)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas~=1.2.5->seeq-azureml) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from pandas~=1.2.5->seeq-azureml) (2.8.1)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.8/site-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets>=7.6.3->seeq-azureml) (0.2.5)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.8/site-packages (from requests>=2.26.0->seeq-azureml) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.8/site-packages (from requests>=2.26.0->seeq-azureml) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.8/site-packages (from requests>=2.26.0->seeq-azureml) (2021.5.30)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
Requirement already satisfied: notebook>=4.4.1 in /opt/conda/lib/python3.8/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (6.4.0)
Requirement already satisfied: Send2Trash>=1.5.0 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (1.5.0)
Requirement already satisfied: prometheus-client in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (0.11.0)
Requirement already satisfied: pyzmq>=17 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (22.1.0)
Requirement already satisfied: argon2-cffi in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (20.1.0)
Requirement already satisfied: nbconvert in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (5.5.0)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (3.0.1)
Requirement already satisfied: terminado>=0.8.3 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (0.10.0)
Requirement already satisfied: cffi>=1.0.0 in /opt/conda/lib/python3.8/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (1.14.5)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.8/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (2.20)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.8/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (2.0.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (1.4.3)
Requirement already satisfied: defusedxml in /opt/conda/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (0.7.1)
Requirement already satisfied: mistune>=0.8.1 in /opt/conda/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (0.8.4)
Requirement already satisfied: entrypoints>=0.2.2 in /opt/conda/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (0.3)
Requirement already satisfied: bleach in /opt/conda/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (3.3.0)
Requirement already satisfied: testpath in /opt/conda/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (0.5.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (20.9)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.8/site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.3->seeq-azureml) (2.4.7)
Installing collected packages: traitlets, charset-normalizer, requests, pandas, ipyvuetify, ipydatetime, seeq-azureml
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour isthe source of the following dependency conflicts.
jupyterhub 1.3.0 requires oauthlib>=3.0, which is not installed.
Successfully installed charset-normalizer-2.0.7 ipydatetime-1.2.0 ipyvuetify-1.8.1 pandas-1.2.5 requests-2.26.0 seeq-azureml-0.1.0 traitlets-5.1.1
datalab@jupyter:~$ python -m seeq.addons.azureml
/opt/conda/bin/python: Error while finding module specification for 'seeq.addons.azureml' (ModuleNotFoundError: No module named 'seeq.addons')`

**Comment by monstrorivas** [comment] 2021-11-15 20:29
@KjellRSeeq what's the Seeq server and SDL server versions? Can you please provide the following as well?

- output of `pip list` from the terminal of the SDL project
- output of `pip show seeq` from the terminal of the SDL project
- In the same terminal, 
     - run `ipython` 
     - run `from seeq import spy`
     - run `spy.__version__`

**Comment by KjellRSeeq** [comment] 2021-11-15 23:04
The Seeq Server version is R52.1.4 and the Seeq Data Lab version (base) is R52.1.4, with seeq module v179.18. I have also been working with Matt Gasbarro to try and determine what could be causing this FYI. It seems that pip installing a new Seeq version works, but when I import seeq in a notebook, it always reverts to the base version for some reason. We have tested and this does not occur for other pkgs, even ones that come base installed with SDL.

Outputs of your requests in this project:
pip list: 
`Package            Version
------------------ -------------
-andas             1.2.5
charset-normalizer 2.0.7
ipydatetime        1.2.0
ipyvuetify         1.8.1
Markdown           3.3.4
packaging          21.2
requests           2.26.0
seeq               52.3.2.182.25
traitlets          5.1.1
tzlocal            2.1`

pip show seeq:
`Name: seeq
Version: 52.3.2.182.25
Summary: The Seeq SDK for Python
Home-page: https://www.seeq.com
Author: Seeq Corporation
Author-email: support@seeq.com
License: UNKNOWN
Location: /home/datalab/.local/lib/python3.8/site-packages
Requires: Markdown, cryptography, Deprecated, recurrent, urllib3, matplotlib, certifi, cron-descriptor, six, pyOpenSSL, ipywidgets, numpy, nbconvert, beautifulsoup4, pandas, notebook, Mako, requests, ipython
Required-by:`

ipython interaction output:
![image](https://user-images.githubusercontent.com/92815457/141866488-6f55276a-ab96-4885-82aa-05e9e2e25b30.png)


At this stage, we might be a few weeks away from an upgrade to R54, which I believe might resolve this issue, but would cause slowdown on Azure ML lighthouse progress.

**Comment by monstrorivas** [comment] 2021-11-16 17:46
It looks like the issue is on the Seeq Data Lab side where for some reason the installed version of `seeq.spy` is not used by the python interpreter. It also looks like this behavior has been fixed in newer versions of Seeq. Thus, the recommendation would be to upgrade the Seeq/SDL servers. 

I'm closing this issue for now, since the root cause and fix are out of the scope of this project.

**Closed as completed by monstrorivas** 2021-11-16 17:46 UTC
Labels: question
